AllCops:
  Include:
    - "*.gemspec"
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
  DisplayCopNames: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/CaseEquality:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25
