AllCops:
  Include:
    - "*.gemspec"
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
  DisplayCopNames: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 160
